[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ignored_error_codes = [
    9302,
] # Ignore the return value warning from low level calls
ignored_warnings_from = ["lib/"] # Ignore warnings from lib path

# Formatter
[fmt]
multiline_func_header = "all" # Or  params_first
contract_new_lines = true
line_length = 120
#bracket_spacing = true
wrap_comments = true
sort_imports = true
number_underscore = "thousands"
ignore = ["./script/**/*", "./lib/**/*"] # Paths to ignore from formatting
single_line_statement_blocks = "single"
single_line_imports = true

# Linter
[lint]
#lint_on_build = false
exclude_lints = ["screaming-snake-case-immutable", "mixed-case-variable"]
ignore = ["./test/**/*"]

# Fuzzing configs
[fuzz]
runs = 512

# Fork testing RPC endpoints
[rpc_endpoints]
eth_sepolia_rpc = "https://eth-sepolia.g.alchemy.com/v2/zhfy5Q8m26qNzni3r-ixkMufWc2mCIb_"
arbitrum_sepolia_rpc = "https://arb-sepolia.g.alchemy.com/v2/zhfy5Q8m26qNzni3r-ixkMufWc2mCIb_"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
